const aidRequestStyles = {
  pageWrapper: {
    display: 'flex',
    flexDirection: 'column',
    minHeight: '100vh',
    background: 'linear-gradient(180deg, #D4E4BC 0%, #E8F5E9 100%)',
  },
  contentContainer: {
    flex: 1,
    padding: '40px 60px',
    position: 'relative',
  },
  filterRow: {
    display: 'flex',
    gap: '15px',
    marginBottom: '40px',
    alignItems: 'center',
    height: '50px', // Prevents layout jump when pills appear
  },
  pillsContainer: {
    display: 'flex',
    gap: '15px',
    animation: 'fadeIn 0.3s ease-in-out',
  },
  filterIconButton: {
    backgroundColor: '#FFF',
    border: 'none',
    borderRadius: '50%',
    width: '45px',
    height: '45px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    boxShadow: '0px 4px 10px rgba(0,0,0,0.1)',
    cursor: 'pointer',
    transition: '0.3s all ease',
  },
  categoryPill: {
    padding: '8px 20px',
    borderRadius: '25px',
    fontWeight: 'bold',
    fontSize: '14px',
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    boxShadow: '0px 4px 10px rgba(0,0,0,0.05)',
    cursor: 'pointer',
    transition: '0.2s all ease',
    userSelect: 'none',
  },
  pillCount: {
    borderRadius: '50%',
    width: '20px',
    height: '20px',
    fontSize: '11px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: '0.2s all ease',
  },
  requestGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(300px, 1fr))',
    gap: '30px',
  },
  requestCard: {
    backgroundColor: '#90D7FF',
    height: '200px',
    borderRadius: '20px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    boxShadow: '0px 8px 20px rgba(0,0,0,0.1)',
  },
  cardContent: { padding: '20px', textAlign: 'left', width: '100%' },
  cardTitle: { margin: '0 0 10px 0', fontSize: '20px', fontWeight: 'bold' },
  cardDetail: { margin: '2px 0', fontSize: '14px', color: '#333' },
  cardTag: {
    marginTop: '15px',
    padding: '5px 12px',
    backgroundColor: '#2D5A27',
    color: '#FFF',
    borderRadius: '15px',
    fontSize: '12px',
    display: 'inline-block'
  },
  createButton: {
    position: 'fixed',
    bottom: '40px',
    right: '40px',
    width: '60px',
    height: '60px',
    borderRadius: '50%',
    backgroundColor: '#2D5A27',
    color: 'white',
    fontSize: '30px',
    border: 'none',
    cursor: 'pointer',
    boxShadow: '0px 10px 20px rgba(0,0,0,0.2)',
    zIndex: 100,
  }
};

export default aidRequestStyles;