const campaignStyles = {
  pageBackground: {
    backgroundColor: '#DEF1E3', 
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column',
    fontFamily: "'Segoe UI', Roboto, 'Helvetica Neue', sans-serif",
  },
  ctaFooterBackground: {
    backgroundColor: '#F5F9F3', 
  },

  navbar: {
    backgroundColor: '#C5E0CC', 
    padding: '20px 40px',
    borderBottom: '1px solid #B0C9B6',
    display: 'flex',
    justifyContent: 'center', 
  },
  searchContainer: {
    display: 'flex',
    gap: '15px',
    alignItems: 'center',
    maxWidth: '1200px',
    width: '100%',
  },
  searchLabel: {
    color: '#333',
    fontWeight: '600',
    fontSize: '14px',
    marginRight: '10px',
  },
  searchInput: {
    padding: '10px 15px',
    border: '1px solid #CCC',
    borderRadius: '4px',
    flex: '1', 
    fontSize: '14px',
    backgroundColor: '#FFF',
  },
  searchDropdown: {
    padding: '10px 35px 10px 15px',
    border: '1px solid #CCC',
    borderRadius: '4px',
    backgroundColor: '#FFF',
    color: '#666',
    fontSize: '14px',
    appearance: 'none', 
    cursor: 'pointer',
    width: '180px',
  },
  dropdownIcon: {
    position: 'absolute',
    right: '10px',
    top: '50%',
    transform: 'translateY(-50%)',
    width: '16px',
    pointerEvents: 'none',
  },
  searchButton: {
    padding: '10px 25px',
    backgroundColor: '#A0A0A0', 
    color: '#FFF',
    border: 'none',
    borderRadius: '4px',
    fontWeight: '600',
    cursor: 'pointer',
    fontSize: '13px',
    textTransform: 'uppercase',
  },

  mainContent: {
    maxWidth: '1200px',
    margin: '0 auto',
    padding: '40px 20px',
    width: '100%',
  },
  headerRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '30px',
  },
  mainHeader: {
    fontSize: '24px',
    color: '#333',
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  sortDropdown: {
    padding: '8px 12px',
    backgroundColor: '#EBEBEB',
    border: '1px solid #D1D1D1',
    borderRadius: '4px',
    color: '#333',
    fontSize: '12px',
    cursor: 'pointer',
  },

  // Campaign Grid
  grid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)', 
    gap: '30px',
    marginBottom: '40px',
  },

  // Campaign Card
  card: {
    backgroundColor: '#FFF',
    borderRadius: '8px',
    overflow: 'hidden',
    boxShadow: '0 2px 8px rgba(0,0,0,0.05)',
    display: 'flex',
    flexDirection: 'column',
  },
  cardImagePlaceHolder: {
    backgroundColor: '#000', 
    height: '200px',
    width: '100%',
  },
  cardContent: {
    padding: '20px',
    display: 'flex',
    flexDirection: 'column',
    flex: 1,
  },
  cardTitle: {
    fontSize: '18px',
    fontWeight: '700',
    color: '#333',
    marginBottom: '10px',
  },
  cardDescription: {
    fontSize: '14px',
    color: '#555',
    lineHeight: '1.6',
    marginBottom: '20px',
    flex: 1,
  },
  fundingLabel: {
    fontSize: '12px',
    color: '#888',
    marginBottom: '5px',
  },
  progressBarBg: {
    height: '6px',
    backgroundColor: '#EBEBEB',
    borderRadius: '3px',
    overflow: 'hidden',
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: '#3CB371', 
  },

  // Pagination
  pagination: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    gap: '10px',
    marginTop: '40px',
    paddingBottom: '40px',
  },
  pageButton: {
    width: '40px',
    height: '40px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '4px',
    border: '1px solid #E1E1E1',
    backgroundColor: '#FFF',
    color: '#666',
    cursor: 'pointer',
    fontSize: '14px',
    fontWeight: '500',
  },
  activePage: {
    backgroundColor: '#A0A0A0',
    color: '#FFF',
    borderColor: '#A0A0A0',
  },
  pageArrow: {
    backgroundColor: 'transparent',
    border: 'none',
    cursor: 'pointer',
    color: '#A0A0A0',
  },

  // CTA Section
  ctaSection: {
    padding: '80px 20px',
    borderTop: '2px solid #000', 
    display: 'flex',
    justifyContent: 'space-between',
    gap: '50px',
    maxWidth: '1200px',
    margin: '0 auto',
  },
  ctaBlock: {
    flex: '1',
    textAlign: 'center',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
  },
  ctaHeader: {
    fontSize: '32px',
    color: '#000',
    fontFamily: "Georgia, 'Times New Roman', Times, serif", 
    marginBottom: '15px',
  },
  ctaText: {
    fontSize: '16px',
    color: '#555',
    lineHeight: '1.8',
    marginBottom: '30px',
    maxWidth: '500px',
  },
  blackButton: {
    padding: '12px 40px',
    backgroundColor: '#000',
    color: '#FFF',
    border: 'none',
    borderRadius: '25px', 
    fontWeight: '600',
    cursor: 'pointer',
    fontSize: '13px',
    textTransform: 'uppercase',
  },

  // Footer
  footer: {
    padding: '60px 20px 40px',
    maxWidth: '1200px',
    margin: '0 auto',
    display: 'grid',
    gridTemplateColumns: '1.5fr 1fr 1fr 1fr 1.5fr', 
    gap: '40px',
  },
  footerColumn: {
    display: 'flex',
    flexDirection: 'column',
  },
  footerHeader: {
    fontSize: '16px',
    fontWeight: '700',
    color: '#333',
    marginBottom: '20px',
  },
  footerText: {
    fontSize: '13px',
    color: '#666',
    lineHeight: '1.6',
    marginBottom: '20px',
  },
  footerLink: {
    fontSize: '13px',
    color: '#666',
    textDecoration: 'none',
    marginBottom: '12px',
    cursor: 'pointer',
  },
  socialIcons: {
    display: 'flex',
    gap: '15px',
    marginTop: '10px',
  },
  socialIcon: {
    width: '24px',
    height: '24px',
    cursor: 'pointer',
  },
  footerInputGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
  },
  footerInput: {
    padding: '10px',
    border: '1px solid #CCC',
    borderRadius: '4px',
    backgroundColor: '#FFF',
    width: '100%',
  },
  smallBlackButton: {
    padding: '8px 15px',
    backgroundColor: '#000',
    color: '#FFF',
    border: 'none',
    borderRadius: '4px',
    fontWeight: '600',
    cursor: 'pointer',
    fontSize: '11px',
    textTransform: 'uppercase',
    alignSelf: 'flex-start',
  },
};

export default campaignStyles;