const contactStyles = {
  pageWrapper: {
    display: 'flex',
    flexDirection: 'column',
    minHeight: '100vh',
    backgroundColor: '#C1D8A8', 
  },
  contentContainer: {
    flex: 1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '60px 40px', 
    gap: '40px',
    background: 'linear-gradient(180deg, #C1D8A8 0%, #D8E6C3 100%)', 
  },
  heroCard: {
    backgroundColor: '#F3F8B9', 
    padding: '60px 40px',
    borderRadius: '30px',
    maxWidth: '500px',
    textAlign: 'center',
    boxShadow: '0px 10px 30px rgba(0,0,0,0.05)',
  },
  heroTitle: {
    fontSize: '42px',
    color: '#4A7C44',
    fontWeight: '900',
    marginBottom: '20px',
    textShadow: '1px 1px 0px #fff',
  },
  divider: {
    height: '2px',
    backgroundColor: '#4A7C44',
    width: '60%',
    margin: '0 auto 20px auto',
    opacity: 0.3,
  },
  heroDescription: {
    fontSize: '20px',
    color: '#333',
    lineHeight: '1.4',
    fontWeight: '600',
  },
  infoGrid: {
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
  },
  topRow: {
    display: 'flex',
    gap: '20px',
  },
  smallCard: {
    backgroundColor: '#FFF',
    padding: '30px',
    borderRadius: '25px',
    width: '180px',
    textAlign: 'center',
    boxShadow: '0px 4px 15px rgba(0,0,0,0.1)',
  },
  wideCard: {
    backgroundColor: '#FFF',
    padding: '20px 30px',
    borderRadius: '25px',
    display: 'flex',
    alignItems: 'center',
    gap: '20px',
    boxShadow: '0px 4px 15px rgba(0,0,0,0.1)',
    position: 'relative',
  },
  iconCircle: {
    backgroundColor: '#222',
    width: '50px',
    height: '50px',
    borderRadius: '12px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardTitle: { fontSize: '18px', margin: '15px 0 5px 0' },
  cardDetail: { fontSize: '14px', fontWeight: 'bold', margin: 0 },
  cardSubDetail: { fontSize: '11px', color: '#888' },
  wideCardText: { flex: 1 },
  cardTitleLeft: { fontSize: '18px', margin: 0 },
  cardDetailLeft: { fontSize: '14px', color: '#666', margin: 0 },
  pinIcon: { width: '30px', height: '30px' }
};

export default contactStyles;